### ISSUE TITLE
Clarity of RTS results

### ISSUE THREAD

**Issue by Schattensilber** [jenkinsci/peass-ci-plugin#111]
### What feature do you want to see added?

The RTS result page gets quite big in our project - especially the coverage based selection output - , would be nice to have some collapsing features or similar to
1) get a quick overview of the chosen tests and
2) still see the details of which tests correspond to which changes.

**Comment by DaGeRe** [comment]
I don't know what exactly you require by this issue. If wanted, please specify your requirements for the overview. If this is not needed anymore, I'll close this issue.

**Comment by DaGeRe** [comment]
Since there are no new requirements on this issue, I'll close it.
