### ISSUE TITLE
Show reason why measurement aborts early

### ISSUE THREAD

**Issue by Schattensilber** [jenkinsci/peass-ci-plugin#112]
### What feature do you want to see added?

When measurements are not successful they abort early, i.e. after three VMs.
While this is a good feature it would be good to communicate this early abortion on the measurement log page.

**Comment by DaGeRe** [comment]
There was an error that led to a reduced count of vm starts at all: https://github.com/DaGeRe/peass/commit/8d5532e0b8d63011a2f8529b8d1711e3e94965ff This should now be fixed.

The log displaying also needs to be fixed.

**Comment by DaGeRe** [comment]
This should now work with https://github.com/jenkinsci/peass-ci-plugin/commit/ea7c56ae3d9568fabde0657a1694baa0770fa043. Can you confirm this?

**Comment by Schattensilber** [comment]
Seems to work fine
