### ISSUE TITLE
Use @Ignore early

### ISSUE THREAD

**Issue by Schattensilber** [jenkinsci/peass-ci-plugin#113]
### What feature do you want to see added?

Currently tests that are set to @Ignore indirectly (I.e. at class level) are still tried to be run by the RTS and then "fail".
This has led me a few times astray to figure out what's wrong.
Peass should only consider tests that are not ignored.

To achive this, the following tasks should be done: 
- [x] Do not use ignored / disabled methods
- [x] Do not use ignored / disabled classes
- [ ] Do not use subclasses of ignored / disabled classes

**Comment by DaGeRe** [comment]
The first task should be finished by https://github.com/DaGeRe/peass/commit/54d828860f0b0984e987be958e7a8ec6d8c70858

**Comment by Schattensilber** [comment]
Second task is finished with [7c90f081a8aee0ffa6cdfa8db678dd9a783f36d6](https://github.com/DaGeRe/peass/commit/7c90f081a8aee0ffa6cdfa8db678dd9a783f36d6)

**Comment by DaGeRe** [comment]
Ignore does not get inherited, therefore, the third task does not need to be finished.
