### ISSUE TITLE
Use localization for measurement values

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#114]
### What feature do you want to see added?

Values in tables should be displayed accordingly browser-localization. So e.g. in german, commas should be used instead of dots.
An example how to internationalize messages can be found [here](https://www.jenkins.io/doc/developer/internationalization/i18n-source-code/).

**Comment by DaGeRe** [comment]
This should work with https://github.com/jenkinsci/peass-ci-plugin/commit/1162a22218c0ba59d3873645b293b7076efa73a2 , can you confirm this?

**Comment by mawHBT** [comment]
Is working now.
