### ISSUE TITLE
Fix histogram labels

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#117]
### What feature do you want to see added?

Some histogram labels don't show prefixes correctly.

![Unbenannt](https://user-images.githubusercontent.com/90041268/158636649-cccde33b-a31d-4c2a-825f-aaca92386ee0.PNG)

**Comment by DaGeRe** [comment]
Thanks for the hint, that is fixed with https://github.com/jenkinsci/peass-ci-plugin/commit/47c18a319a51f61228d5641260a879c8ec69b590
