### ISSUE TITLE
Add parameter excludeLog4jToSlf4j

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#120]
### What feature do you want to see added?

If log4j-to-slf4j is present, following error is thrown:
`org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j`

A parameter should be added to exclude Log4jToSlf4j.

**Comment by mawHBT** [comment]
Parameter was added with [7900b2](https://github.com/DaGeRe/peass/commit/7900b2f41826ca4446398c189a8e727cea473300), a appropriate job is green, but RTS finds no changes.

**Comment by DaGeRe** [comment]
This works now.
