### ISSUE TITLE
Remove JUnit-ecludes from gradle-files

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#125]
### What feature do you want to see added?

KoPeMe needs JUnit-4. If gradle-files contain any JUnit-4 excludes (e.g.  'junit', module: 'junit' and 'org.junit.vintage', module: 'junit-vintage-engine'), these excludes must be removed.

**Comment by DaGeRe** [comment]
After splitting JUnit 4 and 5, this should work now.
Does this work for you?

**Comment by mawHBT** [comment]
Is working now.
