### ISSUE TITLE
Configuration custom Java/SpringBoot plugin via CLI

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#126]
### What feature do you want to see added?

Make custom Java/SpringBoot Plugin name configurable via CLI

**Comment by DaGeRe** [comment]
This required an additional bugfix, since the default values were not set: https://github.com/DaGeRe/peass/commit/645d1afc4c51484478858e1461d7360ec2a7629b Now it works.
