### ISSUE TITLE
Provide Performance Data Analysis for Debugging

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#136]
### What feature do you want to see added?

A jenkins build-step should be implemented to provide Data for debugging.

So you can see the following:
commit-sha
changed Classes/methods
which TestCases call these changes 
Do we measure changes

So if a TestCase calls the changes but is not identified to do so by peass, this will help to debug.

**Comment by DaGeRe** [comment]
Thanks for the issue, this now basically works. Just add `peassAnalysis()` to your pipeline, and you will get a table with the properties of the changes. Does this work for you?

![image](https://user-images.githubusercontent.com/4358467/168051252-b570eaaf-c733-406a-a4b4-5249ce058128.png)

**Comment by mawHBT** [comment]
Works for me on a TestProject local and remote.
