### ISSUE TITLE
Configuration of aspectJ fails, if build.gradle contains no obvious entry for (integration)test-task

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#139]
### What feature do you want to see added?

If aspectJ is used, the appropriate (integration)test-task must be configured in build.gradle. If build.gradle does not contain a obvious entry for this task, peass does not know, that the module contains (integration)tests and does not add the configuration entry.
Editing of GradleBuildfileEditor.addArgLine is necessary.

**Comment by DaGeRe** [comment]
Thanks for the issue (which is a bug). This should be fixed by https://github.com/jenkinsci/peass-ci-plugin/issues/140, but now https://github.com/jenkinsci/peass-ci-plugin/issues/142 should already fix it.

**Comment by mawHBT** [comment]
Fixed by [#142](https://github.com/jenkinsci/peass-ci-plugin/issues/142)
