### ISSUE TITLE
The Visualization of the Call-Tree

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#145]
### What feature do you want to see added?

Only the method name of one method and No call tree is displayed.
 This is linked to point 1 of Issues [#134](https://github.com/jenkinsci/peass-ci-plugin/issues/134)

**Comment by DaGeRe** [comment]
This should work since https://github.com/DaGeRe/peass/commit/bebfb06ec902676a140346c6842b3a4ad8489f07 (Problem was not sufficient space for the svg of the d3-generated tree; this sould be fixed now).
Could you check this?
