### ISSUE TITLE
Include/Exclude by Rule

### ISSUE THREAD

**Issue by Schattensilber** [jenkinsci/peass-ci-plugin#150]
### What feature do you want to see added?

We have two types of tests:
Simple Unit Tests: Just java
Module Tests: java + test db (based on docker)

They would benefit from very different configurations, i.e. the second kind is measureWorkloadOnly, whereas the first can utilize repetitions.

I'd set up two different pipelines for them, but the include/exclude by name config is not powerful enough. Much better would be to differentiate based on the ClassRule DockerRule.

Ideally there could be some --include-by-rule='DockerRule' or similar functionality.

**Comment by DaGeRe** [comment]
Therefore, three tasks need to be executed:

- [ ] Create a unit test for checking whether an classe uses a given rule and implement the checking
- [ ] Create a unit test for checking whether the super class of a java class uses a given rule and implement the checking
- [ ] Add `includeByRule` / `excludeByRule` to `ExecutionConfig`, `ExecutionConfigMixin` and ` MeasureVersionBuilder`

**Comment by DaGeRe** [comment]
The first task is implemented by https://github.com/DaGeRe/peass/commit/8495b1d45d0fc7d692be345ddc85694bc81afa32

**Comment by DaGeRe** [comment]
The second task is implemented since https://github.com/DaGeRe/peass/commit/2746095c2ebfcf611fb6ad0a17d1aa312640efe2

**Comment by Schattensilber** [comment]
I'll test and close if it works

**Comment by DaGeRe** [comment]
Another bugfix was necessary, since https://github.com/DaGeRe/peass/commit/597117154e9a13917e1253882a99a148f32cf0e9 this should work now.
