### ISSUE TITLE
Add permission rules for emulated tests

### ISSUE THREAD

**Issue by alex-iotiq** [jenkinsci/peass-ci-plugin#168]
To be able to write/read files inside the emulator (for temporary results), you have to add permissions. 
Usually those permissions have to be granted at runtime, but with tests you can add a special rule to grant them automatically.

First you need to add permissions 
```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
to `app/src/main/AndroidManifest.xml`:

```xml
<manifest ... package="com.example.android_example">
    ...
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    ...
    <application
        ...
        android:requestLegacyExternalStorage="true"
        ...
    >
```
And then adding permission rules to the tests which are run like this:

```java
import android.Manifest;
import androidx.test.rule.GrantPermissionRule;
import org.junit.Rule;

@RunWith(AndroidJUnit4.class)
public class InstrumentedTest {
...
    @ClassRule
    public static GrantPermissionRule mRuntimePermissionRule = GrantPermissionRule.grant(Manifest.permission.WRITE_EXTERNAL_STORAGE);
    ...
```
- granting `WRITE_EXTERNAL_STORAGE` permission will automatically grant `READ_EXTERNAL_STORAGE`.
- `ClassRule` will grant the permissions before the test is executed, because `build.gradle` is being read before the execution

Add dependency to `app/build.gradle` (related #171):
```groovy
...
dependencies {
    ...
    androidTestImplementation 'androidx.test:rules:1.4.0'
    ...
}
```

This means there are 3 requirements:

- [x] Adapt `AndroidManifest.xml` automatically (Unit test implementation + usage in code)
- [x] Add `ClassRule`
- [x] Add test implementation for `androidx.test:rules`

**Comment by DaGeRe** [comment]
Adding the rule now also works: https://github.com/DaGeRe/peass/commit/f68feef3a69ee5fcf5dcba6ad91cc9ddb6a16409
