### ISSUE TITLE
Add a Parameter for Changing  Explicit Value in Code, this Effect the Execution Time

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#177]
### What feature do you want to see added?

In some cases is the execution time dependet on a variable in code. 
Peass by instrumentation slows down the execution time longer than the execution the same code. If the execution time is dependent on a certain Variable in code, peass cannot change the value.
The solution is to pass value as parameters to adjust the execution time for peass execution.

To achive this, the following tasks should be done:

- [x]  Write Unittest
- [x]  Add parameter "increaseVariableValue" (best as String[]) to Peass (ExecutionConfig)
- [x]  Implementing transformation method
- [x]  Changing JUnitTestTransformer to call transformation method ,if parameter "increaseVariableValue" is set

**Comment by DaGeRe** [comment]
Thank for the groundwork, this should work now: https://github.com/DaGeRe/peass/commit/17f21f43e85b608f2186fc651438a6fbf133d770 Can you confirm this?

**Comment by bam-hbt** [comment]
This was tested. The variable in class has changed.
This works now.
