### ISSUE TITLE
Add parameter for setting a maximum file-size for log-files read by jenkins

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#182]
### What feature do you want to see added?

If a build creates very big logs, reading of build.xml by jenkins after the job has finished can cause an OOM-error. To prevent this, a parameter is needed for setting a maximum file-size. If build.xml is bigger than the maximum, jenkins should not try to read it. So the file still exists for further examination but does not cause the oom-error if read by jenkins.

**Comment by DaGeRe** [comment]
This should work starting with https://github.com/jenkinsci/peass-ci-plugin/commit/57bde495a09603a683788acad53d61902ecadc91, can you confirm this?

**Comment by mawHBT** [comment]
This is working now. If logsize is bigger than importLogSizeInMb they aren't loaded and you get a message instead.

**Comment by DaGeRe** [comment]
Thanks for the feedback, if things are ready, you can also close the issue ;)
