### ISSUE TITLE
delete logfiles bigger than a given size

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#184]
### What feature do you want to see added?

Sometimes logfiles become too big, polluting your discspace. It should be possible, to set a parameter for deleting logfiles exceeding the given size.

**Comment by DaGeRe** [comment]
This should work starting with https://github.com/DaGeRe/peass/commit/71f0b1b45e67fabc93d64898b5b13c477ec96590, can you confirm this?

**Comment by mawHBT** [comment]
I checked this for some days now and it works.
