### ISSUE TITLE
Change System Properties in Build Gradle

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#187]
### What feature do you want to see added?

The configured parallel execution as system property causes an error. Therefore the property in build gradle file should be changed to "SAME_THREAD".

**Comment by bam-hbt** [comment]
This was solved by https://github.com/DaGeRe/peass/pull/91, https://github.com/DaGeRe/peass/pull/93, https://github.com/DaGeRe/peass/pull/94

**Comment by DaGeRe** [comment]
Just a little addition: In general, `MutableBoolean` are a concept that rarely should be used; instead, result objects containing all the results can be used. I refactored this: https://github.com/DaGeRe/peass/commit/40d0375a6de8618d171c3288a4ee318918caf6fc please have a look at how this works.
