### ISSUE TITLE
Set buildstate to unstable if errors occur in measurement for single test

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#194]
### What feature do you want to see added?

We had a build for a single test with an error-free RTS but errors in measurements. Buildstate was green anyways. In this case, buildstate should be set to unstable. There was no error in the build itself. So with other error-free tests you would have appropriate results. Getting an unstable buildstate would let you know that anything did go wrong in single test(s).

**Comment by DaGeRe** [comment]
This should work starting with https://github.com/jenkinsci/peass-ci-plugin/commit/1547616999523d27ec96b67c736cf616815acb4c, does this work for you?

**Comment by mawHBT** [comment]
This did not occur anymore, so I close this.
