### ISSUE TITLE
If jvmArgs already exist in build.gradle, extend them instead of adding a second jvmArgs-line

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#197]
### What feature do you want to see added?

If you set --onlyOneCallRecording, peass configures aspectJ in jvmArgs in build.gradle:
`jvmArgs=["...-aspectj.jar"]`
This adds a second jvmArgs-line if one already exists, causing weird behaviour. In my case -Xmx from the first line took effect while -XX:+HeapDumpOnOutOfMemoryError did not.
To avoid this, existing jvmArgs should just be extended.

**Comment by DaGeRe** [comment]
This should work with https://github.com/DaGeRe/peass/commit/5b789d7294cff37ee61c8f2bb7e8058054428c9d - could you test this?
And if this is not working, could you specify a test case with your task definition syntax and eventually also a fix?

**Comment by mawHBT** [comment]
If a project has:
`jvmArgs=["-XX:+HeapDumpOnOutOfMemoryError", "-Xmx256m"]`
both arguments are added together as one argument, resulting in:
`jvmArgs=["anOldArgument", '-XX:+HeapDumpOnOutOfMemoryError, -Xmx256m']`
This causes an error.

**Comment by mawHBT** [comment]
I checked this locally by instrumentate a project with an existing argLine. This seems to work for test but I still miss:
`jvmArgs=["-javaagent:${System.properties['user.home']}/.m2/repository/net/kieker-monitoring/kieker/1.15.1/kieker-1.15.1-aspectj.jar"`
for integrationTest. This should be there, right?
I started by cleaning up TestJVMArgsGradle for further testing, see [PR#98](https://github.com/DaGeRe/peass/pull/98).

**Comment by DaGeRe** [comment]
There might be a problem with `integrationTest`, it should also be instrumented. Could you create a unit test that proves that `integrationTest` is not adapted correctly, and eventually even provide a fix?

**Comment by mawHBT** [comment]
All I can say, is that the jvmArgs-line configuring aspectj is not added, if there is no (integration)test-block in the gradle file at all. This behaves the same for test and integrationTest.

I added
`testAspectJAddedWithOnlyOneCallRecordingAndTesttasksConfigured` (green)
and
`testAspectJAddedWithOnlyOneCallRecordingAndTesttaskNotConfigured` (red)
in this [PR](https://github.com/DaGeRe/peass/pull/100).

If I now comment the line
`Assert.assertTrue(integrationTestTask.contains(...` in the green `testAspectJAddedWithOnlyOneCallRecordingAndTesttasksConfigured`
and remove everything related to integrationTest from `buildJVMArgsInMegabyte.gradle`, the test suddenly fails. I don't understand why this happens and need further examination.

**Comment by mawHBT** [comment]
Since extension of jvmArgs works in general, I close this ticket. For the problem of not adding aspectJ-jar I opened [#202](https://github.com/jenkinsci/peass-ci-plugin/issues/202).
