### ISSUE TITLE
Make heapsize configurable for gradle

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#198]
### What feature do you want to see added?

If you have a test in a gradle-project which needs more than the default heapsize, you should be able to set a parameter configuring heapsize for test-execution.

**Comment by DaGeRe** [comment]
After a bunch of changes (latest https://github.com/DaGeRe/peass/commit/64cee5a239257d479203dbf20cb3770f5052c57d), this should work in general.
Could you test this, and if it does not work, provide a unit test for the problematic gradle syntax, and if it works, add a configuration option in Peass-CI?

**Comment by mawHBT** [comment]
If I set xmx: '1g' for a test which failed with OOM-error before, the test is green. RTS and measurements are successful. So this seems to work. The option for setting this in the pipeline has been made available with [commit 2072ef1](https://github.com/jenkinsci/peass-ci-plugin/commit/2072ef1eec5bf61cc45e02a49de636ee6ed81c8e).
