### ISSUE TITLE
Mocked Static Execution Should Be Measurable

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#204]
### What feature do you want to see added?

Kopeme runs the tests in a separate thread and the mocking static methods in a local thread-mock.
Also, JUnit 5 starts the test initialization (including @BeforeAll), and then KoPeMe starts the test control later in the test cycle, and then starts BeforeAll again. However, since mock static instances are supposed to be closed, running BeforeAll multiple times will give an exception.
Therefore, the Kopeme should be capable of calling the @beforAll method in the same thread.

**Comment by DaGeRe** [comment]
Thanks for the hint, calling `@BeforeAll` in the same thread and clearing the mockito cache should work starting with https://github.com/DaGeRe/peass/commit/c8f6fa35dfb51cbb948c5b2d8f60fa4371431f44 - can you confirm this?

**Comment by bam-hbt** [comment]
JUnitTestTransformer add "_peass_initializeMockito()" method to other test class, they didn't use any Mockito. Therefore, miss Mockito import in these classes.
This PR fixes the problem: https://github.com/DaGeRe/peass/pull/110

**Comment by bam-hbt** [comment]
This should fix that: https://github.com/DaGeRe/peass/pull/111

**Comment by bam-hbt** [comment]
Thanks for fix, looks fine.
