### ISSUE TITLE
Show Warning If Tests in Current Commit not executed

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#206]
### What feature do you want to see added?

It can be confusing if the result or message is not displayed in the regression test selection log overview. It can be happened, when Trace for some test not be created.

**Comment by DaGeRe** [comment]
Thanks for the hint. That should be clearer to the user.
I've added some popups for making this easier to understand: https://github.com/jenkinsci/peass-ci-plugin/commit/26f68e05880f1fc3320e018bcd0ae21fb4311083 does this help?

**Comment by bam-hbt** [comment]
Thanks for fix, looks fine.
