### ISSUE TITLE
Fix dashboard-link for "inspect node"

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#212]
### What feature do you want to see added?

In the overview for rca of a single test, you can see "Inspect node" under the histogram. Link for it is broken and you get error 404.

**Comment by DaGeRe** [comment]
Thanks for the hint, it seems like https://github.com/jenkinsci/peass-ci-plugin/commit/5ccab5d5e681f1b53e3f4a8fa8ca483f129d926b#diff-4f017ab14f84a83c771cd700b9e94b32dc2105cd85ae64d0bea5412cc2dc1d32R295 made the link unusable.

**Comment by DaGeRe** [comment]
This should work starting with https://github.com/jenkinsci/peass-ci-plugin/commit/48f911b9c88921c0ca625f546afc146ce49fd8a3, can you confirm this?

**Comment by mawHBT** [comment]
Seems to work again, so I close this.
