### ISSUE TITLE
--timeout option doesn't change the waiting period

### ISSUE THREAD

**Issue by alex-iotiq** [jenkinsci/peass-ci-plugin#213]
The timeout is always 5 minutes regardless of the `-timeout` option.
It may be related to `-useAnbox` option. 

And log says "Waiting for 300 _**minutes**_", shouldn't it be "Waiting for 300 **_seconds_**" ?

**Comment by DaGeRe** [comment]
Thanks for the hint with the minutes, this is fixed: https://github.com/DaGeRe/peass/commit/b8f8aaf551d39a723771296acba62cf73c242cdc

Could you further specify when this happens? On RTS, Measurement, RCA, everytime...?

**Comment by alex-iotiq** [comment]
This happens in ProcessSuccessTester probably on RTS

**Comment by DaGeRe** [comment]
Currently, I cannot reproduce this issue.
Could you set breakpoints at all constructor calls to `ExecutionConfig`  and tell me the stack trace where this happens?

**Comment by alex-iotiq** [comment]
It looks like it's working now. It was probably a configuration error on my side.
