### ISSUE TITLE
ClearMockitoCaches Leads to Missing Inline Mocked Objects

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#217]
### What feature do you want to see added?

If the class is mocked-inline, after clean up mockito caches the mocked obj will be lost.

**Comment by DaGeRe** [comment]
Thanks for the issue. I've created a test for this: https://github.com/DaGeRe/peass/commit/10b824abe79bb1bc8c85d6b77dae3ec8814177c2 and will fix this now.

**Comment by DaGeRe** [comment]
To clarify this for future reference: This was about having mock initializing directly at field declaration, e.g.

```
public class MyTest {
  public static final Object myMock = Mockito.mock(Object.class);

  @Test
  public void doSomething(){ 
    Assert.assertEquals("asdasd", mock.toString());
  }
}
```

To fix this, the initialization needs to be moved to the `@BeforeAll` method (or, in case of a field variable, to `@BeforeEach`).

There is no relation to mockito-inline.
