### ISSUE TITLE
CleanPerformanceMeasurement does'nt Clean up All Masseurement Files

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#219]
### What feature do you want to see added?

After clean meassurement still Json File under _peass Folder exists. With reduce the VM Count, we get old Json File with failure

**Comment by DaGeRe** [comment]
This should be fixed with https://github.com/jenkinsci/peass-ci-plugin/commit/cb10172465b949b87ed9ff97b9fca70a564b30d7, can you confirm this?

**Comment by bam-hbt** [comment]
Thanks for fix, looks fine.
