### ISSUE TITLE
Show only latest RCA action

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#220]
### What feature do you want to see added?

If you use:
`cleanPerformanceMeasurement cleanRTS: false, cleanMeasurement: false`
meaning you just repeat RCA, using the previous results for RTS and measurement, with each build a new RCA-action is added.
Only one RCA-action should be displayed.
![multiplaRCAactions](https://user-images.githubusercontent.com/90041268/212677676-bd8d2dc4-a348-4824-b1cc-de74f58e1a7c.PNG)

**Comment by bam-hbt** [comment]
This should be fixed by https://github.com/DaGeRe/peass/commit/2a82ee8c60f38dbcdf824aa6387b6e77de36c1c1. Does this work for you?

**Comment by mawHBT** [comment]
I ran a complete build for one of our exampleTests. After that, two times RCA only (using cleanPerformanceMeasurement cleanRTS: false, cleanMeasurement: false). I got only one RCA-action, those from previous builds are not shown anymore. So this seems to work.
