### ISSUE TITLE
Make Read Commit History Configurable

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#227]
### What feature do you want to see added?

Peass reads commits linearly by default. It is useful to be able to read commits non-linearly if the commits are not on the same path.

**Comment by bam-hbt** [comment]
Peas Pull Request: https://github.com/DaGeRe/peass/pull/143
Peass-Ci Pull Request: https://github.com/jenkinsci/peass-ci-plugin/pull/229

**Comment by DaGeRe** [comment]
This should work now and could be closed, right?

**Comment by bam-hbt** [comment]
It's working.
