### ISSUE TITLE
Develop OnlyMergeStaticTestSelection

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#233]
### What feature do you want to see added?

We need to merge many RTS test results. It makes sense to further develop "OnlyMergeStaticTestSelection" to merge all JSON files.

**Comment by DaGeRe** [comment]
This should be possible starting with https://github.com/DaGeRe/peass/commit/856146a83d5bbe6b5010a75b488fa7669efd6029 - can you test it?

**Comment by bam-hbt** [comment]
It's working now!
