### ISSUE TITLE
Don't add kieker-dependency twice

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#234]
### What feature do you want to see added?

On instrumentation, "net.kieker-monitoring:kieker:x.x.x" is added twice to dependencies in gradle-file:
```
dependencies {
    implementation libs.azure.blob
    implementation libs.spring.kafka
    testImplementation libs.spring.kafka.test
implementation 'de.dagere.kopeme:kopeme-junit5:1.3.3' // Added dynamically by Peass.
implementation 'net.kieker-monitoring:kieker:1.15.2' // Added dynamically by Peass.
implementation 'net.kieker-monitoring:kieker:1.15.2' // Added dynamically by Peass.
}
```
Probably this does not matter, but it better should not happen.

**Comment by bam-hbt** [comment]
That should fix this problem: https://github.com/DaGeRe/peass/pull/149

**Comment by mawHBT** [comment]
I checked this with same select call, now I got:
```
implementation 'de.dagere.kopeme:kopeme-junit5:1.3.4' // Added dynamically by Peass.
implementation 'net.kieker-monitoring:kieker:1.15.2' // Added dynamically by Peass.
implementation 'net.kieker-monitoring:kieker:1.15.2:aspectj' // Added dynamically by Peass.
```
Is aspectj correct? Thought this should only be added when --onlyOneCallRecording is used? (Or aspectj is actively set.)
I'm confused, since the once doubled dependency got replaced by another one?

**Comment by mawHBT** [comment]
Ok, thank's for explaining! So everything seems correct here. Issue can be closed, I guess.
