### ISSUE TITLE
First Character Missing for Root Cause Analysis Actions

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#57]
In some cases, the first character of each testname is missing in Root Cause Analysis Actions.

**Comment by DaGeRe** [comment]
Thanks for the hint, this should be fixed with https://github.com/jenkinsci/peass-ci-plugin/commit/95a2445d7132cf8fe3d5963379e4cbda0cd567e8

**Comment by mawHBT** [comment]
This is working now.
