### ISSUE TITLE
Regression Test Selection fails with untraceable error

### ISSUE THREAD

**Issue by Schattensilber** [jenkinsci/peass-ci-plugin#58]
### Reproduction steps

- project compilation runs through, no error in maven build log
- "regression test selection log overview" shows errors for these maven logs
- no tests are actually run 
- not sure how to reproduce, admin has view access to repo

### Results

Expected result:

Should continue to build traces and select tests.

Actual result:

Stops after compilation, but no compilation error can be seen.

**Comment by DaGeRe** [comment]
This seems to be because of a wrong output of the regression test selection, it is sometimes marked as failed even if it ran correctly. This should be fixed in https://github.com/jenkinsci/peass-ci-plugin/commit/22b9609222cb90d1e75decdbee27de51b7bb4d18

**Comment by Schattensilber** [comment]
Fixed.
