### ISSUE TITLE
Warning in RTS Log Overview if no changes present

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#59]
If no changes are found (because there are none), you get a misleading message in Regression Test Selection Log Overview:
"Warning: The regression test selection had an error, and no log files were produced for the current version."
Build is green with no errors, Log-files are present. But you still get the warning

**Comment by DaGeRe** [comment]
Thanks for the hint, this should work starting with https://github.com/jenkinsci/peass-ci-plugin/commit/2c2c5afacb816bd2bb7975be0e8fe49977a25786, can you confirm this?

**Comment by mawHBT** [comment]
This works now, no errormessage is shown anymore.
