### ISSUE TITLE
Confusing info when no test selected

### ISSUE THREAD

**Issue by Schattensilber** [jenkinsci/peass-ci-plugin#60]
When no test is selected the run is successful, this makes sense. But when checking the test selection view there is a warning:
```
 Warning: The regression test selection had an error, and no log files were produced for the current version. 
```
But all the trace creation runs are clean.

In this case there should be an information like
```
No changes in any method called by any tests detected.
```

**Comment by DaGeRe** [comment]
Thanks for the hint, this works since https://github.com/jenkinsci/peass-ci-plugin/commit/a9f3a7844e89bf3a05dc3642bd7718f634c7f7f8
