### ISSUE TITLE
Support Custom Module projectDir

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#67]
If names of module-directories are modified, for example like this:

rootProject.children.each { subproject ->
    subproject.projectDir = file("module-" + subproject.name)
    subproject.buildFileName = "${subproject.name}.gradle"
}

peass can not find the directories, because it still searches for the unmodified directory-names.

**Comment by DaGeRe** [comment]
Thanks for the issue, this should be fixed in https://github.com/DaGeRe/peass/commit/314cfc40f6177d6adf2b7c98df9b64432fd91479, can you confirm this?

**Comment by mawHBT** [comment]
This works now.
