### ISSUE TITLE
Give an info when selected tests were not run

### ISSUE THREAD

**Issue by Schattensilber** [jenkinsci/peass-ci-plugin#68]
So we had a testclass that was set to @Ignore, and changes in the traces of some of the tests inside this testclass.
It took a while to figure this out, since I wasn't at the time aware that the class was ignored. The RTS showed that these tests had changes in their traces and I expected them to be measured, and wondering why not.

Please show some hint in RTS-overview when tests don't run, especially when they are on ignore...

**Comment by alex-iotiq** [comment]
A related issue. Tests shown in Trace Creation Runs are not flagged when a run is not successful.
In my case it is because the tests are not found, which is related to this issue: https://github.com/jenkinsci/peass-ci-plugin/issues/72

**Comment by DaGeRe** [comment]
Thanks for the hint, this should work with the newest commit on develop - everytime no trace is created, an exclamation mark should appear, like this:

![grafik](https://user-images.githubusercontent.com/4358467/145987492-f0a6080c-15c6-489a-a1bb-c48965ce7b70.png)

Does this also work for you?

**Comment by Schattensilber** [comment]
Newest development build gives visible warning in the log overview. This is great for finding out quickly when there's an issue. Please give some reference to this also in the rts results window, since I'd check there first.

**Comment by alex-iotiq** [comment]
This Issue is now resolved. 
Flags are working now for logs in `Current Version Run` and `Predecessor Version Run`
