### ISSUE TITLE
Log Redirection Also Redirects Logs of Different Jobs

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#70]

**Comment by mawHBT** [comment]
[JenkinsLogRedirector](https://github.com/jenkinsci/peass-ci-plugin/blob/main/src/main/java/de/dagere/peass/ci/process/JenkinsLogRedirector.java) redirects all current System.out to the RTS-Logfile. This includes also the output of other currently running jobs. So RTS-Logfile contains not only output of specific job, but also output of other currently running jobs.

**Comment by DaGeRe** [comment]
Thanks for the issue! 

The solution seems to be to only redirect logs from the current thread. Could you check whether this works with commit https://github.com/jenkinsci/peass-ci-plugin/commit/6d2bdac8011b95a15105f97a51976a65afee22ed ? (This is the newest commit on develop)

**Comment by bam-hbt** [comment]
I already test the same Scenario and it seems good. I didn't find output of other currently running jobs.

**Comment by DaGeRe** [comment]
Thanks for the quick response.

I'll close this for now, if you see the error again feel free to re-open the issue.
