### ISSUE TITLE
Option to specify test directory

### ISSUE THREAD

**Issue by alex-iotiq** [jenkinsci/peass-ci-plugin#72]
In Android projects there are usually 2 test directories `androidTest` and `test`.
To avoid wrong selected tests, it would be great to specify which directory should be used to find the correct tests.

**Comment by DaGeRe** [comment]
Thanks for the idea. This should work starting with https://github.com/jenkinsci/peass-ci-plugin/commit/9c3df35663555f80d1fb0e67e7d911d789cc8b77, can you confirm this?
