### ISSUE TITLE
Add parameter "failOnRtsError"

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#78]
If there are errors in Regression Test selection for a number of tests, you get a general warning in the Regression Test Selection Results:
"Warning: An error occured during trace getting execution. Please check the logs for details and consider fixing the configuration or excluding the erroneous test cases."

Also for a specific test, in the Regression Test Selection Log Overview, by hovering over the red exclamation mark you can see:
"Regression test selection had error"

The build itself will still be succesfull. To notice, if such errors occur, a Parameter "failOnRtsError" should be added. Setting it should let the build fail in such cases.

As condition 
_tests.getLogSummary().isErrorInCurrentVersionOccured() || tests.getLogSummary().isErrorInPredecessorVersionOccured()_
can be used. If true, call _Run.setResult(Result.FAILURE)_.

**Comment by DaGeRe** [comment]
As we discussed, you will primarily implement this. You can ask me about details if problems occur.

**Comment by DaGeRe** [comment]
If I see this correctly, this is done by https://github.com/jenkinsci/peass-ci-plugin/pull/86, right? If so, you can close this issue.

**Comment by mawHBT** [comment]
Implemented with [9410488](https://github.com/jenkinsci/peass-ci-plugin/commit/9410488d2445318fa08802687c9f6a351ee46bfa) and [a96eabf](https://github.com/jenkinsci/peass-ci-plugin/commit/a96eabfd7e6d1cdda9eb62b2a0d7891441c466a8)
