### ISSUE TITLE
Fix Problems with Big Traces

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#79]
### What feature do you want to see added?

If generated traces for regression test selection become too big, Jenkins can run out of memory. To avoid this, a flag (e.g. "useSimpleTrace") should be added. If set, each method-executing should be recorded only oncy.

**Comment by DaGeRe** [comment]
Thanks for the idea.

This should work with https://github.com/jenkinsci/peass-ci-plugin/commit/3937b8dcfdf9adfc20ae4416c4c5d14c0d28ddb1 - now, you can configure `onlyOneCallRecording`. If it is set, only that a method is called will be recorded (but not their order). Thereby, big traces can be handled (but there will be no exact traces anymore, but just lists of recorded methods).

Does this work for you?

**Comment by DaGeRe** [comment]
I think, this works for the regression test selection now.

Since we have a similiar problem for RCA and you opened a new issue for it (https://github.com/jenkinsci/peass-ci-plugin/issues/81), can we close this issue?

**Comment by mawHBT** [comment]
For RTS this works.
