### ISSUE TITLE
Add Timeout-Info for user 

### ISSUE THREAD

**Issue by bam-hbt** [jenkinsci/peass-ci-plugin#83]
### What feature do you want to see added?

The Timeout Parameter in last build will be lost and after new build we can't follow the Timeout-Info.

**Comment by DaGeRe** [comment]
This seems to be the same as https://github.com/jenkinsci/peass-ci-plugin/issues/195. Since there is no additional information, I'll close this one - please reopen if this is wrong and further specify what to do here.
