### ISSUE TITLE
Fix Unit of Measurement Values

### ISSUE THREAD

**Issue by DaGeRe** [jenkinsci/peass-ci-plugin#84]
### What feature do you want to see added?

Measurement values are currently displayed as as microseconds (https://github.com/jenkinsci/peass-ci-plugin/blob/18793792f9043b3d90d05d830e5e0fe428873a8f/src/main/resources/de/dagere/peass/ci/MeasureVersionAction/index.jelly#L111) or as micro- or nanoseconds depending on the value (https://github.com/jenkinsci/peass-ci-plugin/blob/18793792f9043b3d90d05d830e5e0fe428873a8f/src/main/resources/de/dagere/peass/ci/MeasureVersionAction/measurements.jelly#L55).

For values bigger than microseconds, i.e. milliseconds or seconds, this does not make sense. Therefore, it would be nice if a method for providing the measurements in a suitable unit could be added.

**Comment by mawHBT** [comment]
This works for MeasureVersionAction but has to be implemented in all the other places where measurement values are displayed.
