### ISSUE TITLE
cleanPerformanceMeasurement() should also clean jenkins_home/jobs/jobName/peass-data

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#93]
### What feature do you want to see added?

If the step cleanPerformanceMeasurement() is used, all files from previous builds in jenkins_home/workspace/jobName are deleted.

But files in jenkins_home/jobs/jobName/peass-data remain. If full cleaning is intended, peass-data should also be cleaned.

**Comment by mawHBT** [comment]
This is related to [Issue #82](https://github.com/jenkinsci/peass-ci-plugin/issues/82). So no new issue is neede.

**Comment by DaGeRe** [comment]
Thanks for the hint. This should work with https://github.com/jenkinsci/peass-ci-plugin/commit/cfbc713dac74e40864d7a9cb519955ad3625e0b1, can you confirm this?

**Comment by mawHBT** [comment]
Works now.
